{{- if .Values.createNamespace.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: {{ template "opentelemetry-operator.namespace" . }}
{{- end }}
